const STREAM="https://stream.zeno.fm/7u0fw8vmzneuv";
const radio=document.getElementById("radio"), play=document.getElementById("play"), stop=document.getElementById("stop"), status=document.getElementById("status"), install=document.getElementById("install"), share=document.getElementById("share");
radio.src=STREAM;
play.addEventListener("click", async()=>{try{await radio.play();status.textContent="Radio en direct — bonne écoute !"}catch(e){status.textContent="Impossible de démarrer la radio. Vérifiez votre connexion et réessayez."}});
stop.addEventListener("click",()=>{radio.pause();radio.currentTime=0;status.textContent="Radio arrêtée"});
radio.addEventListener("error",()=>status.textContent="Le flux n’est pas disponible pour le moment. Réessayez dans quelques instants.");
let deferredPrompt;
window.addEventListener("beforeinstallprompt",(e)=>{e.preventDefault();deferredPrompt=e;install.hidden=false});
install.addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;install.hidden=true});
share.addEventListener("click",async()=>{if(navigator.share){await navigator.share({title:"Radio Source Divine",text:"Écoutez Radio Source Divine en direct."})}else{await navigator.clipboard.writeText(location.href);share.textContent="Lien copié !"}});
if("serviceWorker" in navigator) window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
